name: Scrape Data Workflow

on:
  push:
    branches:
      - main  # Jalankan workflow saat push ke branch 'main'
  workflow_dispatch:  # Izinkan menjalankan workflow secara manual

jobs:
  scrape_data:
    runs-on: ubuntu-latest  # Gunakan runner Ubuntu terbaru

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Clone repository

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Gunakan Python 3.10

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npx playwright install --with-deps chromium  # Install Playwright dan Chromium

      - name: Run Scraping Script
        run: python scrape.py

      - name: Compress Dataset to ZIP
        run: |
          sudo apt-get update
          sudo apt-get install -y zip  # Pastikan zip terinstal
          zip -r dataset.zip dataset/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: scraped_data.zip
          path: dataset.zip
