name: Scrape Club Data

on: [push]  # Jalankan saat push ke repository

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      # Checkout kode dari repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Instal dependensi
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4 pycountry tenacity
          playwright install --with-deps

      # Debug: Tampilkan isi direktori
      - name: List directory contents
        run: ls -la

      # Jalankan script
      - name: Run scrape.py
        run: python scrape.py
